### PR TITLE
Summary as code

### LINKED ISSUE #194: write wrap up of tutorial as code

### PR DESCRIPTION
**Pull request by aaronpeikert**
@cjvanlissa asked for a wrap up of the tutorial. Here it is.

closes #194

### CODE REVIEW

**Review by brandmaier — COMMENTED** [review]
I recommend removing the verbatim quotes of the metadata  bits to shorten this whole paragraph. Keep the line that says you have to adjust the metadata and refer back to earlier where you explained this already (you DID explain this before, right?). Otherwise it's somehow too redundant.

**Comment by aaronpeikert** [comment]
@brandmaier If you feel strongly about it, we can remove the metadata, but I think the summary can not be too redundant but should be "complete" to be helpful.

**Comment by brandmaier** [comment]
No strong feelings. Completeness is probably a good thing here.

**Comment by aaronpeikert** [comment]
Good!

**Pull request merged**
